spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: config-server-dev
user:
  name: kongzhao
  age: 33
  sex: male
---
spring:
  profiles: pro
  application:
    name: config-server-pro
